import {dayStatus,summarize,normalizeSourceUrl,dayNumber} from './lib/tracker.mjs';
const $ = selector => document.querySelector(selector);
const expandedDays=new Map();
let records,filter='all',query='',mode='snapshot',warning='',toastTimer;
const esc = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateLabel = date => new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(`${date}T12:00:00Z`));
const source = url => normalizeSourceUrl(url);
function link(url,text,cls='source-link'){const safe=source(url);return safe?`<a class="${cls}" href="${esc(safe)}" target="_blank" rel="noopener noreferrer">${text}</a>`:'';}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2800);}
function releaseCard(r){return `<article class="release-card"><div class="release-heading"><h3>${esc(r.title)}</h3><span class="category ${esc(r.category.toLowerCase())}">${esc(r.category)}</span>${link(r.source_url,'<span class="source-x">𝕏</span> Source ↗')}</div><p>${esc(r.summary)}</p></article>`;}
function resetNotice(d){if(d.reset_status==='confirmed')return `<article class="reset-notice"><span aria-hidden="true">↻</span><div><strong>Reset confirmed</strong><p>${esc(d.note)}</p>${link(d.reset_source_url,'See the reset announcement ↗')}</div></article>`;if(d.poll_url)return `<article class="reset-notice"><span aria-hidden="true">↻</span><div><strong>Reset pending</strong><p>${esc(d.note)}</p>${link(d.poll_url,'View Tibo’s reset poll ↗')}</div></article>`;return '';}
function render(){const summary=summarize(records.days,records.releases);$('#shipped-score').textContent=summary.shippedDays;$('#release-score').textContent=summary.totalReleases;$('#reset-score').textContent=summary.confirmedResets;$('#all-count').textContent=summary.totalReleases;$('#progress-bar').style.width=`${summary.shippedDays/28*100}%`;
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const current=dayNumber(today);
$('#day-board').innerHTML=records.days.map(d=>{const count=records.releases.filter(r=>r.day===d.day).length;const state=dayStatus(d);const label=state==='pending'?(d.date>today?'Upcoming':'Unverified'):state.replaceAll('-',' ');return `<button class="day-tile ${state} ${d.day===current?'current':''}" data-day="${d.day}" aria-label="Day ${d.day}, ${dateLabel(d.date)}, ${esc(label)}, ${count} releases${d.reset_status==='pending'?', reset unconfirmed':''}"><span class="tile-number">${String(d.day).padStart(2,'0')}</span><span class="tile-icon">${state==='shipped-and-reset'?'↗ ↻':state==='shipped'?'↗':state==='reset'?'↻':'·'}</span>${count>1?`<span class="tile-count">×${count}</span>`:''}</button>`;}).join('');renderTimeline();renderStatus();}
function renderStatus(){const checked=records.challenge.verified_at;const status=mode==='supabase'?`Updated ${checked}`:`Snapshot · ${checked}`;$('#data-status').textContent=warning?`${status}. ${warning}`:status;}
function activityBadges(d,count){return `<span class="day-activity">${count?`<span class="activity-badge feature-badge">↗ ${count} feature${count===1?'':'s'}</span>`:''}${d.reset_status==='confirmed'?'<span class="activity-badge reset-badge">↻ Reset</span>':d.poll_url||d.reset_status==='pending'?'<span class="activity-badge pending-badge">↻ Reset pending</span>':''}</span>`;}
function renderTimeline(){const term=query.toLowerCase();const releases=records.releases.filter(r=>`${r.title} ${r.summary} ${r.category} day ${r.day}`.toLowerCase().includes(term));
const days=[...records.days].reverse().filter(d=>filter==='resets'?((d.reset_status==='confirmed'||!!d.poll_url)&&(!term||`reset ${d.note} day ${d.day}`.toLowerCase().includes(term))):releases.some(r=>r.day===d.day)||(filter==='all'&&!term&&(d.reset_status==='confirmed'||!!d.poll_url)));
$('#timeline').innerHTML=days.length?days.map(d=>{const drops=filter==='resets'?[]:releases.filter(r=>r.day===d.day);return `<details class="day-group" data-timeline-day="${d.day}" ${term||(expandedDays.get(d.day)??d.day===days[0].day)?'open':''}><summary class="day-label"><strong>DAY ${String(d.day).padStart(2,'0')}</strong><span>${dateLabel(d.date)}, 2026</span><span class="label-line"></span>${activityBadges(d,drops.length)}</summary><div class="day-content">${drops.map(releaseCard).join('')}${term?'':resetNotice(d)}</div></details>`;}).join(''):`<div class="empty-state"><h3>${query?'No results':'No confirmed resets yet.'}</h3><p>${query?'Try another feature name or clear the search.':'Only a source confirming delivery earns a reset badge.'}</p><button class="outline-button" id="clear-filter">Show all</button></div>`;}
function showDay(number){const d=records.days.find(d=>d.day===number);if(!d)return;const drops=records.releases.filter(r=>r.day===number);$('#day-detail').innerHTML=`<span class="eyebrow muted">${dateLabel(d.date).toUpperCase()}, 2026</span><div class="dialog-day">Day ${String(number).padStart(2,'0')}<span class="lime">.</span></div><div class="dialog-status"><span class="dialog-badge">${drops.length} release${drops.length===1?'':'s'}</span><span class="dialog-badge">${d.reset_status==='confirmed'?'Reset confirmed':'Reset unconfirmed'}</span></div><p class="dialog-note">${esc(d.note)}</p>${drops.length?drops.map(releaseCard).join(''):'<div class="dialog-placeholder">No releases yet.</div>'}${resetNotice(d)}`;$('#day-dialog').showModal();}
function validRecords(value){return value?.challenge&&Array.isArray(value.days)&&value.days.length===28&&Array.isArray(value.releases)&&value.days.every((d,i)=>d.day===i+1&&dayNumber(d.date)===d.day)&&value.releases.every(r=>typeof r.id==='string'&&typeof r.title==='string'&&typeof r.summary==='string'&&typeof r.category==='string'&&r.day>=1&&r.day<=28&&source(r.source_url));}
async function load(){const button=$('#refresh');button.disabled=true;button.textContent='↻ Loading';warning='';try{const response=await fetch('/api/tracker',{cache:'no-store',signal:AbortSignal.timeout(12000)});if(!response.ok)throw new Error('Storage unavailable');const data=await response.json();if(!validRecords(data))throw new Error('Invalid records');records=data;mode=data.mode||'snapshot';warning=data.warning||'';}catch{if(records){warning='Refresh failed; showing the last loaded records.';toast('Couldn’t refresh. Your last loaded records are still here.');}else{try{const response=await fetch('/data/seed.json');if(!response.ok)throw new Error();const data=await response.json();if(!validRecords(data))throw new Error();records=data;mode='snapshot';}catch{$('#timeline').innerHTML='<div class="empty-state"><h3>Receipts are temporarily unavailable.</h3><p>Try Refresh again in a moment.</p></div>';return;}}}finally{button.disabled=false;button.textContent='↻ Refresh';}if(records)render();}
document.addEventListener('click',event=>{const heading=event.target.closest('summary.day-label');if(heading){const group=heading.parentElement;expandedDays.set(Number(group.dataset.timelineDay),!group.open);}const day=event.target.closest('[data-day]');if(day)showDay(Number(day.dataset.day));const tab=event.target.closest('[data-filter]');if(tab){filter=tab.dataset.filter;document.querySelectorAll('[data-filter]').forEach(t=>{t.classList.toggle('active',t===tab);t.setAttribute('aria-pressed',String(t===tab));});renderTimeline();}if(event.target.closest('#clear-filter')){query='';$('#search').value='';document.querySelector('[data-filter=all]').click();}if(event.target.closest('.dialog-close'))event.target.closest('dialog').close();});

$('#search').addEventListener('input',event=>{query=event.target.value;renderTimeline();});$('#refresh').addEventListener('click',load);document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const box=d.getBoundingClientRect();if(e.clientX<box.left||e.clientX>box.right||e.clientY<box.top||e.clientY>box.bottom)d.close();}}));

load();
