import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir, readFile } from 'node:fs/promises';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const outputDir=process.env.VERIFICATION_DIR || 'verification';
await mkdir(outputDir, { recursive: true });
try {
  for (const viewport of [{width:1440,height:1000},{width:390,height:844}]) {
    const page = await browser.newPage({ viewport });
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    const trackerUrl=process.env.TRACKER_URL || 'https://ship-happens-rho.vercel.app';
    if(process.env.LOCAL_BUILD){for(const asset of ['index.html','styles.css','clean.css','app.mjs']){await page.route(new URL(asset==='index.html'?'/':`/${asset}`,trackerUrl).href,async route=>route.fulfill({body:await readFile(`dist/${asset}`),contentType:asset.endsWith('.css')?'text/css':asset.endsWith('.mjs')?'text/javascript':'text/html'}));}}
    await page.goto(trackerUrl);
    await page.waitForFunction(() => getComputedStyle(document.body).backgroundColor === 'rgb(255, 255, 255)');
    await page.waitForFunction(() => document.querySelector('#data-status')?.textContent.includes('Updated'));
    await page.context().grantPermissions(['clipboard-read','clipboard-write'],{origin:new URL(trackerUrl).origin});
    await page.locator('#agent-open').click();
    const prompt=await page.locator('#agent-prompt').inputValue();
    await page.locator('#copy-agent-prompt').click();
    await page.waitForFunction(()=>document.querySelector('#copy-status').textContent==='Copied');
    assert.equal((await page.evaluate(()=>navigator.clipboard.readText())).replaceAll('\r\n','\n'),prompt);
    await page.screenshot({path:`${outputDir}/agent-${viewport.width}.png`,fullPage:true});
    await page.evaluate(()=>Object.defineProperty(navigator.clipboard,'writeText',{configurable:true,value:async()=>{throw new Error('Denied')}}));
    await page.locator('#copy-agent-prompt').click();
    await page.waitForFunction(()=>document.querySelector('#copy-status').textContent.startsWith('Copy unavailable'));
    assert.equal(await page.locator('#agent-prompt').evaluate(e=>e.selectionEnd-e.selectionStart),prompt.length);
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#agent-dialog').evaluate(e=>e.open),false);
    assert.equal(await page.locator('[data-day]').count(), 28);
    assert.equal(await page.locator('#timeline .release-card').count(), 7);
    const newest=page.locator('#timeline details').first();
    const older=page.locator('#timeline details').last();
    assert.equal(await newest.getAttribute('open'), '');
    assert.equal(await older.getAttribute('open'), null);
    await newest.locator('summary').click();
    assert.equal(await newest.locator('.release-card').first().isVisible(), false);
    await newest.locator('summary').focus();
    await page.keyboard.press('Enter');
    assert.equal(await newest.locator('.release-card').first().isVisible(), true);
    await older.locator('summary').click();
    assert.equal(await older.locator('.release-card').first().isVisible(), true);
    await page.locator('#refresh').click();
    await page.waitForFunction(() => !document.querySelector('#refresh').disabled);
    assert.equal(await older.locator('.release-card').first().isVisible(), true);
    await page.locator('#search').fill('Decisions');
    assert.equal(await page.locator('#timeline .release-card').count(), 1);
    assert.equal(await page.locator('#timeline .release-card').isVisible(), true);
    await page.locator('#search').fill('');
    assert.equal(await page.locator('[data-save], [data-filter=saved], .verified, #release-heading').count(), 0);
    assert.equal(await page.locator('#timeline .release-heading .source-link').count(), 7);
    const categoryColors=await page.locator('#timeline .category').evaluateAll(items=>[...new Set(items.map(e=>getComputedStyle(e).backgroundColor))]);
    assert.equal(categoryColors.length, 4);
    await page.locator('[data-filter=resets]').click();
    assert.equal(await page.locator('#timeline .reset-notice').count(), 2);
    assert.equal(await page.locator('#reset-days').textContent(), '2');
    await page.locator('[data-day="2"]').click();
    assert.equal(await page.locator('#day-detail .day-content > .release-card').count(), 4);
    assert.equal(await page.locator('#day-detail .day-content').evaluate(e=>getComputedStyle(e).borderRadius),viewport.width<681?'10px':'12px');
    await page.screenshot({path:`${outputDir}/modal-${viewport.width}.png`,fullPage:true});
    assert.equal(await page.locator('#day-detail .dialog-badge').count(), 2);
    assert.match(await page.locator('#day-detail .dialog-status').innerText(), /Reset confirmed/);
    await page.getByRole('button', {name:'Close day details'}).click();
    await page.locator('[data-filter=all]').click();
    await page.locator('#refresh').click();
    await page.waitForFunction(() => !document.querySelector('#refresh').disabled);
    assert.equal(await page.locator('#celebrate, .hero-description, #confetti').count(), 0);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({path:`${outputDir}/live-${viewport.width}.png`,fullPage:true});
    assert.equal(await page.locator('.pending-badge').count(), 0);
    const confirmed=JSON.parse(await readFile('data/seed.json','utf8'));
    confirmed.days[0].reset_status='confirmed';
    confirmed.days[0].reset_source_url=confirmed.releases[0].source_url;
    confirmed.days[0].note='Confirmed reset fixture for browser verification.';
    await page.route(new URL('/api/tracker',trackerUrl).href,route=>route.fulfill({json:confirmed}));
    await page.locator('#refresh').click();
    await page.waitForFunction(() => !document.querySelector('#refresh').disabled);
    assert.equal(await page.locator('#reset-days').innerText(), '3');
    assert.equal(await page.locator('#timeline .reset-badge').count(), 3);
    await page.locator('[data-filter=resets]').click();
    assert.equal(await page.locator('#timeline .reset-notice').count(), 3);
    await page.locator('[data-day="1"]').click();
    assert.match(await page.locator('#day-detail .dialog-status').innerText(), /Reset confirmed/);
    const banner=page.locator('#day-detail .reset-notice');
    assert.equal(await banner.evaluate(e=>getComputedStyle(e).borderLeftWidth), '4px');
    assert.equal(await banner.evaluate(e=>getComputedStyle(e).backgroundColor), 'rgb(240, 240, 240)');
    await page.screenshot({path:`${outputDir}/confirmed-reset-modal-${viewport.width}.png`,fullPage:true});
    assert.deepEqual(errors, []);
    console.log(`PASS ${viewport.width}px: storage, board, search, collapsible days, keyboard, compact rows, category colors, resets, dialog, refresh, minimal hero, overflow`);
    await page.close();
  }
} finally { await browser.close(); }
